name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
  runs-on: ubuntu-latest 
    permissions:
      contents: read
      pull-requests: write
    uses: vidyasagarreddyc/githubactions1/.github/workflows/a.yml@main
    with:
      config-path: "abc"
    secrets:
      token: "test-hello"
