name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true # Set to false if you want this to be optional
        type: string
      app_version:
        description: 'The application version to deploy'
        required: false
        default: 'latest'
        type: string
      var1:
        description: 'First variable'
        required: false
        default: 'latest'
        type: string
      var2:
        description: 'Second variable'
        required: false
        default: 'latest'
        type: string

  workflow_dispatch:
    inputs:
      app_version:
        description: 'The application version to deploy'
        required: false
        default: 'latest'

jobs:
  run-based-on-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check if environment input is passed
        if: ${{ inputs.environment != '' }} # Check if the input is not empty
        run: |
          echo "Environment input is passed: ${{ inputs.environment }}"
          echo "considr=ered as workflow_call

  run-based-on-2:
    runs-on: ubuntu-latest
    steps:
      - name: Handle missing environment input
        if: ${{ inputs.environment == '' }} # Check if the input is empty
        run: |
          echo "Error: 'environment' input is not passed."
          echo "considr=ered as workflow_dispatch"
