name: Reusable Workflow

on:
  workflow_call:
    inputs:
      event_type:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Type
        run: echo "Event Type:  ${{ github.event.inputs.event_type }}"
