name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
    inputs:
      Pass_Input:
        description: 'test'
        required: true
        default: "From Github action 2"

jobs:
  set_input_job:
    runs-on: ubuntu-latest
    environment: prd
    outputs:
      my_input: ${{ steps.set_input.outputs.my_input }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "${{ vars.test }}"
      - name: Set Input
        id: set_input
        run: echo "::set-output name=my_input::${{ vars.test }}"

  call-workflow-passing-data:
    uses: vidyasagarreddyc/githubactions1/.github/workflows/option1.yml@main
    with:
      MT_NAME: "Calling from Github 2"
      MT_FOLDER: ${{ needs.set_input_job.outputs.my_input }}
      environment: 'prd'

