name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
      Pass_Input:
        description: 'test'
        required: true
        default: "From Github action 2"

jobs:
  call-workflow-passing-data:
    uses: vidyasagarreddyc/githubactions1/.github/workflows/option1.yml@main
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prd
    strategy:
      matrix:
        MT_NAME: "test"
        MT_FOLDER: ${{ vars.VAR1 }}
