name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
      Pass_Input:
        description: 'test'
        required: true
        default: "From Github action 2"

jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prd
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Run other workflow
        uses: vidyasagarreddyc/githubactions1/.github/workflows/option1.yml@main
        with:
          MT_NAME: "Calling from Github 2"
          MT_FOLDER: ${{ secrets.VAR1 }}
