name: "Caller Workflow"
on:
  push:
    branches:
      - main

jobs:
  call-reusable-action:
    uses: vidyasagarreddyc/githubactions1/.github/workflows/secret_reusable.yml@main
    with:
      json_file: input.json
