name: "Caller Workflow secret"
on:
  push:
    branches:
      - main

jobs:
  call-reusable-action:
    uses: vidyasagarreddyc/githubactions1/.github/workflows/secret_reusable.yml@main
    secrets:
      TEST_SECRET: "abcd"
